name: Deploy to Production (Hostinger VPS)

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Hostinger VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            echo "Starting deployment for vendy-buildr..."

            # Define project directory
            PROJECT_DIR="/var/www/vendy-buildr"
            REPO_URL="https://github.com/mayurbagewadi/vendy-buildr.git"
            BRANCH="production"

            # Create project directory if it doesn't exist
            if [ ! -d "$PROJECT_DIR" ]; then
              echo "Creating project directory..."
              mkdir -p $PROJECT_DIR
            fi

            cd $PROJECT_DIR

            # Fix git ownership issue
            git config --global --add safe.directory $PROJECT_DIR

            # Clone or pull the repository
            if [ ! -d ".git" ]; then
              echo "Cloning repository..."
              git clone -b $BRANCH $REPO_URL . || { echo "Git clone failed!"; exit 1; }
            else
              echo "Pulling latest changes..."
              git fetch origin $BRANCH || { echo "Git fetch failed!"; exit 1; }
              git reset --hard origin/$BRANCH || { echo "Git reset failed!"; exit 1; }
              git clean -fd
            fi

            echo "Current commit: $(git rev-parse HEAD)"
            echo "Current branch: $(git branch --show-current)"

            # Install dependencies
            echo "Installing dependencies..."
            npm ci --production=false || { echo "npm install failed!"; exit 1; }

            # Build the project
            echo "Building project..."
            npm run build || { echo "Build failed!"; exit 1; }

            # Verify build output
            if [ ! -f "dist/index.html" ]; then
              echo "ERROR: dist/index.html not found after build!"
              exit 1
            fi

            echo "Build successful! Checking dist/index.html:"
            head -20 dist/index.html

            # Set correct permissions
            echo "Setting permissions..."
            chown -R www-data:www-data $PROJECT_DIR
            chmod -R 755 $PROJECT_DIR

            # Check for SSL certificates
            echo "Checking SSL certificates..."
            if [ ! -f "/etc/letsencrypt/live/yesgive.shop/fullchain.pem" ] || [ ! -f "/etc/letsencrypt/live/yesgive.shop/privkey.pem" ]; then
              echo "WARNING: SSL certificates not found!"
              echo "Please ensure you have a wildcard SSL certificate for *.yesgive.shop"
              echo "Run: certbot certonly --manual --preferred-challenges dns -d yesgive.shop -d *.yesgive.shop"
              echo "Or use your hosting provider's SSL management interface"
              exit 1
            fi
            echo "SSL certificates found and valid!"

            # Setup/reload Nginx with subdomain support
            echo "Setting up Nginx configuration with subdomain support and HTTPS..."
            cat > /etc/nginx/sites-available/vendy-buildr << 'EOF'
            # Redirect HTTP to HTTPS
            server {
                listen 80;
                listen [::]:80;
                server_name yesgive.shop *.yesgive.shop;

                # Redirect all HTTP traffic to HTTPS
                return 301 https://$host$request_uri;
            }

            # Main HTTPS server block with wildcard subdomain support
            server {
                listen 443 ssl http2;
                listen [::]:443 ssl http2;

                # Wildcard domain to catch all subdomains
                server_name yesgive.shop *.yesgive.shop;

                # SSL Certificate (wildcard cert for *.yesgive.shop)
                ssl_certificate /etc/letsencrypt/live/yesgive.shop/fullchain.pem;
                ssl_certificate_key /etc/letsencrypt/live/yesgive.shop/privkey.pem;
                ssl_protocols TLSv1.2 TLSv1.3;
                ssl_ciphers HIGH:!aNULL:!MD5;
                ssl_prefer_server_ciphers on;

                root /var/www/vendy-buildr/dist;
                index index.html;

                # Logs
                access_log /var/log/nginx/yesgive-access.log;
                error_log /var/log/nginx/yesgive-error.log;

                # Gzip compression
                gzip on;
                gzip_vary on;
                gzip_min_length 1024;
                gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml+rss application/json application/javascript;

                # Security headers
                add_header X-Frame-Options "DENY" always;
                add_header X-Content-Type-Options "nosniff" always;
                add_header X-XSS-Protection "1; mode=block" always;
                add_header Referrer-Policy "strict-origin-when-cross-origin" always;

                # Static assets with caching
                location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
                    expires 1y;
                    add_header Cache-Control "public, immutable";
                    access_log off;
                }

                # SPA fallback - CRITICAL FOR REACT ROUTER AND SUBDOMAIN ROUTING
                location / {
                    try_files $uri $uri/ /index.html;
                    add_header Cache-Control "no-cache, no-store, must-revalidate";
                    add_header Pragma "no-cache";
                    add_header Expires 0;
                }

                # Deny access to hidden files
                location ~ /\. {
                    deny all;
                    access_log off;
                    log_not_found off;
                }
            }
            EOF

            # Enable the site
            ln -sf /etc/nginx/sites-available/vendy-buildr /etc/nginx/sites-enabled/vendy-buildr

            # Remove default site if exists
            rm -f /etc/nginx/sites-enabled/default

            # Test and reload Nginx
            nginx -t && systemctl reload nginx || { echo "Nginx configuration test failed!"; exit 1; }

            echo "Deployment completed successfully!"
            echo "Site is live at: https://yesgive.shop"
            echo "All subdomains (e.g., storename.yesgive.shop) are also accessible via HTTPS"
